Гладских Артем
vsuet/cards pull request #21
Opened 2022-10-05 16:13 UTC by IIIIIIIb

Выполнил задание, извините что с  опозданием, в следующий буду выполнять в сроки.

2022-10-05 16:14 UTC, IIIIIIIb commented
Исп-215

2022-10-06 10:21 UTC, anst-foto requested changes
Выровняйте код пожалуйста.

2022-10-06 10:21 UTC, anst-foto commented on DOCUMENT.html
> +            <div class="f1">
Что за класс `f1`? Как из его имени понять что он делает?

2022-10-06 10:21 UTC, anst-foto commented on DOCUMENT.html
> +                    </h3>
Использовать для подписи картинки `h3` немного странно

2022-10-06 10:21 UTC, anst-foto commented on style.css
> + }
Практически ничем не отличаются классы. И зачем было плодить лишние сущности?

2022-10-06 10:21 UTC, anst-foto commented on style.css
> +    display: flex;
Желательно как-то по порядки прописывать свойства.

2022-10-06 19:52 UTC, closed without merging